---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: fluence-l2
  namespace: kube-system
spec:
  serviceSelector:
    matchLabels:
      fluence: cloudless.dev  
  externalIPs: true
  loadBalancerIPs: true
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: fluence-l2
  namespace: kube-system
spec:
  serviceSelector:
    matchLabels:
      fluence: cloudless.dev     

