machine:
  network:
    hostname: ${hostname}
  kubelet:
    extraArgs:
      rotate-server-certificates: true
    extraConfig:
      cpuManagerPolicy: "static"
      cpuManagerPolicyOptions:
        full-pcpus-only: "true"

cluster:
  allowSchedulingOnControlPlanes: true
  network:
    cni:
      name: none
  proxy:
    disabled: true

  controllerManager:
    # for prometheus to scrape
    extraArgs:
      bind-address: 0.0.0.0
      
  scheduler:
    # for prometheus to scrape
    extraArgs:
      bind-address: 0.0.0.0
