apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v1.4.0/kubevirt-operator.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.4.0/kubevirt-cr.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.60.3/cdi-operator.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.60.3/cdi-cr.yaml
replicas:
  - name: virt-controller
    count: 1
  - name: virt-operator
    count: 1
patches:
  - target:
      kind: KubeVirt
      apiVersion: kubevirt.io/v1
      name: kubevirt
      namespace: kubevirt
    path: feature-gates.yml
