apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - podmonitor.yaml
  - alerts.yaml
configMapGenerator:
  - name: flux-grafana-dashboards
    files:
      - dashboards/control-plane.json
      - dashboards/cluster.json
      - dashboards/logs.json
    options:
      annotations:
        grafana_folder: "Flux"
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: spectrum-monitoring
        app.kubernetes.io/component: flux
        kustomize.toolkit.fluxcd.io/substitute: disabled
