apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs-dynamic-localpv-provisioner
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://openebs.github.io/dynamic-localpv-provisioner

