apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lightmare-monitoring
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/components/monitoring/configs/lightmare
  prune: true
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  dependsOn:
    - name: lightmare
      namespace: flux-system
