apiVersion: v1
kind: Service
metadata:
  name: chain-rpc
  labels:
    app: chain-rpc
spec:
  type: ClusterIP
  ports:
    - port: 8545
      targetPort: 8545
      protocol: TCP
      name: rpc
  selector:
    app: chain-rpc
