apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/kubernetes-dashboard
  - ../../apps/external-dns
  - ../../apps/ingress-nginx
  - ../../apps/cert-manager
  - ../../apps/homepage
  - ../../core/local-path-provisioner
  - ../../core/metrics-server
  - ../../core/kubelet-serving-cert-approver
  - ../../core/openebs
  - ../../components/kubevirt
  - ../../components/monitoring
  - hubble-ingress.yml
  - grafana-ingress.yml
  - openebs-mayastor.yml
  #  - cilium-l2.yml
  - lightmare.yml
