apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/external-dns
  - ../../apps/ingress-nginx
  - ../../apps/cert-manager
  - ../../core/kubernetes-dashboard
  - ../../core/kubevirt
