---
apiVersion: v1
kind: Secret
metadata:
  name: fluence-monitoring-creds
  namespace: monitoring
type: Opaque
stringData:
  username: "spectrum"
  password: "Bjyx629kSsVtmiAS"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluence-monitoring-push
  namespace: monitoring
data:
  metrics.yaml: |
    prometheus:
      prometheusSpec:
        remoteWrite:
          - url: https://metrics.fluence.dev/api/v1/push
            basicAuth:
              username:
                name: fluence-monitoring-creds
                key: username
              password:
                name: fluence-monitoring-creds
                key: password

  logs.yaml: |
    promtail:
      config:
        clients:
          - url: http://loki-stack:3100/loki/api/v1/push
          - url: https://logs.fluence.dev/loki/api/v1/push
            basic_auth:
              username: "spectrum"
              password: "Bjyx629kSsVtmiAS"
