apiVersion: v1
kind: Secret
metadata:
  name: fluence-observability-push
  namespace: monitoring
type: Opaque
stringData:
  metrics.yaml: |
    prometheus:
      prometheusSpec:
        remoteWrite:
          - url: https://metrics.fluence.dev
            basicAuth:
              username: 'spectrum'
              password: 'Bjyx629kSsVtmiAS'
