---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 1m
  path: "./flux/core/openebs"
  prune: true
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  