---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs-do-pool
  namespace: flux-system
spec:
  dependsOn:
    - name: openebs
  interval: 1m
  path: "./flux/components/openebs-do-pool"
  prune: true
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
