---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-1
parameters:
  protocol: nvmf
  repl: "1"
provisioner: io.openebs.csi-mayastor
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: ebs-pool
  namespace: openebs
spec:
  node: cp-0
  disks: ["aio:///dev/disk/by-id/placeholder"]
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 1m
  path: "./flux/core/openebs"
  prune: true
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  patches:
    - patch: |-
        - op: replace
          path: /spec/disks
          value: ["aio:///dev/disk/by-id/scsi-0DO_Volume_rnd-mayastor-test-spectrum-cp"]
      target:
        kind: DiskPool
        name: ebs-pool
        namespace: openebs
