apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repository.yaml
  - helm-release.yaml

configMapGenerator:
  - name: cilium-values
    namespace: cilium
    files:
      - values.yaml
