apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  values:
    controller:
      kind: DaemonSet
      publishService:
        enabled: true
      service:
        type: LoadBalancer
        externalIPs:
          - ${LOADBALANCER_IP}
        nodePorts:
          http: 30100
          https: 30101
        externalTrafficPolicy: Local
    ingress:
      enabled: true
      hosts:
        - kube.${DOMAIN}
      ingressClassName: nginx
      useDefaultAnnotations: true
      pathType: ImplementationSpecific
      path: /
      issuer:
        name: letsencrypt
        scope: cluster
      tls:
        enabled: true
