- search:
    provider: [google]
    focus: false
    target: _blank
- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "Cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
