apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: lightmare
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/core/lightmare/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
