apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/core/openebs/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
