apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
  targetNamespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      version: 4.1.3
      sourceRef:
        name: openebs
        kind: HelmRepository
        namespace: flux-system
      install:
        createNamespace: true
  values:
    mayastor:
      csi:
        node:
          initContainers:
            enabled: false
      etcd:
        replicaCount: 1
    engines:
      replicated:
        mayastor:
          enabled: true
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
