---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs-do-pool
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./flux/components/openebs-do-pool/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  dependsOn:
    - name: openebs
