---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor
parameters:
  protocol: nvmf
  repl: "1"
provisioner: io.openebs.csi-mayastor
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: ebs-pool
  namespace: openebs
spec:
  node: cp-0
  disks: ["aio:///dev/disk/by-id/placeholder"]
