---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/components/monitoring/controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-configs
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: monitoring-controllers
  path: ./flux/components/monitoring/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
