apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt-monitoring
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/monitoring/configs/kubevirt
  prune: true
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  dependsOn:
    - name: kubevirt
      namespace: flux-system
