apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yml
  - release.yml
patches:
  - target:
      kind: PersistentVolumeClaim
      name: ccp-proofs-pvc
    path: pvc-patch.yml
