apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lightmare
  namespace: lightmare
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chartRef:
    kind: OCIRepository
    name: lightmare
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: chain-adapter-config
      optional: false
  values:
    operator:
      image:
        repository: "docker.fluence.dev/lightmare"
        tag: "fix-pdev-102-ws-subscription-fix-a2d4a00-2004-1@sha256:fec444b393c18102bca80c5811c8242a20f56d9b25c947dbbee494e8025ca9fc"
      config:
        ccp:
          image:
            repository: "fluencelabs/ccp-cu-worker"
            tag: "0.16.12@sha256:82699d5fe834175c911fc064223ff09810a33274d12a6ac355dc36fdbd4743b6"
          memory: 2.48 gib
