apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lightmare
  namespace: lightmare
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chartRef:
    kind: OCIRepository
    name: lightmare
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: chain-adapter-config
      optional: false
  values:
    operator:
      image:
        repository: "docker.fluence.dev/lightmare"
        tag: "feature-spectr-45-c7f37e2-1816-1@sha256:a03b2bf9aa1ce365f1ce742f68a9cb4ba660d62b37657886bc408a7630477465"
      config:
        ccp:
          image:
            repository: "fluencelabs/ccp-cu-worker"
            tag: "0.16.12@sha256:82699d5fe834175c911fc064223ff09810a33274d12a6ac355dc36fdbd4743b6"
          memory: 2.48 gib
