apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lightmare
  namespace: lightmare
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chartRef:
    kind: OCIRepository
    name: lightmare
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: chain-adapter-config
      optional: false
  values:
    operator:
      image:
        repository: "fluencelabs/lightmare"
        tag: "0.4.0@sha256:b8fe219089f5c4d46463dcc4e0df746e37524e4cf7f97ed3b94979a5ae4bfe8a"
      config:
        ccp:
          image:
            repository: "fluencelabs/ccp-cu-worker"
            tag: "0.17.0@sha256:e2704500147b4c385e1047728e8158c6e6614a519ab8c0bd27eae79aece8d2f1"
          memory: 2.48 gib
