apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lightmare
  namespace: lightmare
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chartRef:
    kind: OCIRepository
    name: lightmare
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: chain-adapter-config
      optional: false
  values:
    operator:
      image:
        repository: "docker.fluence.dev/lightmare"
        tag: "release-please-a6d9ef6-1927-1@sha256:763322384f6cc5f6aea1ee7f23ac1cf5f0e0095b9e8cdc2a5d8fa16863aaccf0"
      config:
        ccp:
          image:
            repository: "fluencelabs/ccp-cu-worker"
            tag: "0.16.12@sha256:82699d5fe834175c911fc064223ff09810a33274d12a6ac355dc36fdbd4743b6"
          memory: 2.48 gib
