apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lightmare
  namespace: lightmare
spec:
  interval: 5m
  chart:
    spec:
      chartRef:
        kind: OCIRepository
        name: lightmare-chart
        namespace: flux-system
  values:
    image:
      repository: fluencelabs/lightmare
      tag: main
      pullPolicy: Always
