apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lightmare
  namespace: lightmare
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chartRef:
    kind: OCIRepository
    name: lightmare
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: chain-adapter-config
      optional: false
  values:
    operator:
      image:
        repository: "docker.fluence.dev/lightmare"
        tag: "feature-pdev-107@sha256:805187aa0bc43075641ef8fccde64a3687bf695a26b3d6932d800d5f03954fa3"
      config:
        ccp:
          type: "mocked"
          proof_period: "7 minutes"
