apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lightmare
  namespace: lightmare
  annotations:
    fluxcd.io/reconcileAt: "2025-03-03T12:00:00Z"
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: lightmare
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: chain-adapter-config
      optional: false
  values:
    operator:
      image:
        repository: "fluencelabs/lightmare"
        tag: "0.3.2@sha256:dfce2c7c0148e555069f8c37fad05bfe7b4978cf54370702331e8b62c7764871"
      config:
        ccp:
          image:
            repository: "fluencelabs/ccp-cu-worker"
            tag: "0.16.3@sha256:ed447bfa1a38fa26e256b3ef641438fa8f09ff688a5654a3ce42fdb5569ca6bd"
