apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lightmare
  namespace: lightmare
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: lightmare
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: chain-adapter-config
      optional: false
  values:
    operator:
      image:
        repository: "fluencelabs/lightmare"
        tag: "0.3.0@sha256:60bd4f7b22f15d94faa569c9f77e4ecde030fce031f8e5a6c09dfc3e652aeb8e"
      config:
        ccp:
          image:
            repository: "fluencelabs/ccp-cu-worker"
            tag: "0.16.2@sha256:2d8a0b6c744fee3bfbf6b7cd3859542a42a5961d96ec66a0b5c0c1728da7c170"
