apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lightmare
  namespace: lightmare
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    force: true
    remediation:
      retries: 3
  chartRef:
    kind: OCIRepository
    name: lightmare
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: chain-adapter-config
      optional: false
  values:
    operator:
      image:
        repository: "fluencelabs/lightmare"
        tag: "0.3.1@sha256:3d0672342051251348379ae9cd7cc2fecd8a34ba8970182e5111733321d2300b"
      config:
        ccp:
          image:
            repository: "fluencelabs/ccp-cu-worker"
            tag: "0.16.2@sha256:2d8a0b6c744fee3bfbf6b7cd3859542a42a5961d96ec66a0b5c0c1728da7c170"
