apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lightmare
  namespace: lightmare
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chartRef:
    kind: OCIRepository
    name: lightmare
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: chain-adapter-config
      optional: false
  values:
    operator:
      image:
        repository: "docker.fluence.dev/lightmare"
        tag: "feature-pdev-97-cff75f2-1868-1@sha256:4a815d27872e4655a20da6cba5765fb49f1976a23b67adfc018c3937cfd4ec7f"
      config:
        ccp:
          image:
            repository: "fluencelabs/ccp-cu-worker"
            tag: "0.16.12@sha256:82699d5fe834175c911fc064223ff09810a33274d12a6ac355dc36fdbd4743b6"
          memory: 2.48 gib
