apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs-mayastor
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: mayastor
      version: 2.7.3
      sourceRef:
        name: openebs-mayastor
        kind: HelmRepository
        namespace: flux-system
  values:
      etcd:
        replicaCount: 1
      csi:
        node:
          initContainers:
            enabled: false
