apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs/openebs
      sourceRef:
        name: openebs
        kind: HelmRepository
        namespace: flux-system
