apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt
  namespace: flux-system
spec:
  interval: 1m0s
  path: "./flux/components/kubevirt/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  validation: client
