apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/dev/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
