apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/apps/cert-manager/manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-issuer
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./flux/apps/cert-manager/issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  dependsOn:
    - name: cert-manager
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: terraform-config
