apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt-app
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  wait: true
  path: "./deploy"
  sourceRef:
    kind: GitRepository
    name: kubevirt-flux
