apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipfs
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
        - name: ipfs
          image: ipfs/kubo:v0.27.0
          ports:
            - containerPort: 5001
            - containerPort: 4001
          env:
            - name: IPFS_PROFILE
              value: "server"
          volumeMounts:
            - name: ipfs-storage
              mountPath: /data/ipfs
      volumes:
        - name: ipfs-storage
          persistentVolumeClaim:
            claimName: ipfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ipfs
  labels:
    app: ipfs
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
    - port: 4001
      targetPort: 4001
      protocol: TCP
  selector:
    app: ipfs
