apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-node
  labels:
    app: graph-node
spec:
  selector:
    matchLabels:
      app: graph-node
  template:
    metadata:
      labels:
        app: graph-node
    spec:
      containers:
        - name: graph-node
          image: fluencelabs/graph-node:v0.35.1
          ports:
            - containerPort: 8000
            - containerPort: 8001
            - containerPort: 8020
            - containerPort: 8030
            - containerPort: 8040
          env:
            - name: postgres_host
              value: "postgres.chain.svc.cluster.local"
            - name: postgres_user
              value: "graph-node"
            - name: postgres_pass
              value: "let-me-in"
            - name: postgres_db
              value: "graph-node"
            - name: ipfs
              value: "ipfs.chain.svc.cluster.local:5001"
            - name: ethereum
              value: "local:http://chain-rpc.chain.svc.cluster.local:8545"
            - name: GRAPH_LOG
              value: "info"
            - name: ETHEREUM_REORG_THRESHOLD
              value: "1"
            - name: ETHEREUM_ANCESTOR_COUNT
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: graph-node
  labels:
    app: graph-node
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: api
    - port: 8020
      targetPort: 8020
      protocol: TCP
      name: admin
  selector:
    app: graph-node
