apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 5m
  chart:
    spec:
      chart: oauth2-proxy
      version: 6.23.1
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt"
      path: /oauth2
      hosts: 
        - &host auth.${DOMAIN}
      tls:
        - hosts:
          - *host
          secretName: oauth2-tls
    extraArgs:
      provider: oidc
      oidc-issuer-url: https://${AUTH0_DOMAIN}/
      cookie-domain: .${DOMAIN}
      client-id: "${AUTH0_CLIENT_ID}"
      client-secret: "${AUTH0_CLIENT_SECRET}"
      cookie-secret: "${AUTH0_COOKIE}"
      set-authorization-header: true
      whitelist-domain: .${DOMAIN}
      email-domain: "*"
      pass-access-token: true
      reverse-proxy: true
      code-challenge-method: S256
