apiVersion: v1
kind: Secret
metadata:
  name: auth0
  namespace: oauth2-proxy
data:
  values.yaml: |-
    config:
      clientID: "${AUTH0_CLIENT_ID}"
      clientSecret: "${AUTH0_CLIENT_SECRET}"
      cookieSecret: "${AUTH0_COOKIE}"
