apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      - name: DO_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-digitalocean
            key: token
    logLevel: debug
    txtOwnerId: "rnd-setup-ingress"
    sources:
      - ingress
    policy: sync
    provider: digitalocean
