apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
configMapGenerator:
  - name: dashboards-node-exporter
    files:
      - dashboards/node_exporter.json
    options:
      annotations:
        grafana_folder: "System"
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/component: system
        app.kubernetes.io/part-of: spectrum-monitoring
