apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
commonAnnotations:
  grafana_folder: "Kubernetes"
  app.kubernetes.io/component: monitoring

configMapGenerator:
  - name: dashboards-node-exporter
    files:
      - dashboards/node_exporter.json
    options:
      labels:
        grafana_folder: "System"

  - name: dashboards-k8s-views-global
    files:
      - https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/refs/tags/v2.5.3/dashboards/k8s-views-global.json

  - name: dashboards-k8s-views-namespaces
    files:
      - https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/refs/tags/v2.5.3/dashboards/k8s-views-namespaces.json

  - name: dashboards-k8s-views-nodes
    files:
      - https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/refs/tags/v2.5.3/dashboards/k8s-views-nodes.json

  - name: dashboards-k8s-views-pods
    files:
      - https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/refs/tags/v2.5.3/dashboards/k8s-views-pods.json
