bookmarks.yaml: |
  ---
  - Developer:
    - Github:
        - abbr: GH
          href: https://github.com/
services.yaml: |
  ---
widgets.yaml: |
  ---
  - search:
      provider: [google]
      focus: false
      target: _blank
  - kubernetes:
      cluster:
        show: true
        cpu: true
        memory: true
        showLabel: true
        label: "Cluster"
      nodes:
        show: true
        cpu: true
        memory: true
        showLabel: true
kubernetes.yaml: |
  ---
  mode: cluster
settings.yaml: |
  ---
  title: Spectrum Dashboard
  favicon: https://kubernetes.io/images/favicon.png
  theme: dark
  color: blue
  target: _self
  headerStyle: clean
  layout:
    Home:
      style: row
      columns: 4
