apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  values:
    image:
      tag: v1.0.4
      repository: ghcr.io/gethomepage/homepage
    serviceAccount:
      create: true
      name: homepage
    enableRbac: true
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt"
        hosts:
          - host: &host "home.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: homepage-tls
    config:
      bookmarks:
        - Spectrum:
          - Github:
              - href: https://github.com/fluencelabs/spectrum/tree/${BRANCH}
                description: "Spectrum config"
                icon: github.png
          - Github:
              - abbr: PR
                href: ${PR_URL}
                description: "PR that triggered cluster creation"

      kubernetes:
        mode: cluster

      settings:
        title: Spectrum Dashboard
        favicon: https://kubernetes.io/images/favicon.png
        theme: dark
        color: slate
        target: _self
        headerStyle: clean
        layout:
          Home:
            style: row
            columns: 4

      widgets:
        - search:
            provider: [duckduckgo]
            focus: false
            target: _blank
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
            nodes:
              show: false

      services: null
