apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-issuer
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./flux/dev/cert-issuer/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  dependsOn:
    - name: cert-manager
