{
 "title": "Lightmare",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kubevirt_vm_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Cores in use",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_vmi_node_cpu_affinity)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM in use",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_vmi_memory_domain_bytes) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CCP Hashrate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(ccp_checked_hashes_count)", "legendFormat": "Hashrate" }
   ]
  },
  {
   "title": "VM Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    { "expr": "kubevirt_vm_info", "legendFormat": "__auto" },
    { "expr": "kubevirt_vmi_node_cpu_affinity", "legendFormat": "__auto" },
    {
     "expr": "kubevirt_vmi_memory_domain_bytes / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (name,exported_namespace)(rate(kubevirt_vmi_vcpu_seconds_total[1m]))",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Network IO, receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kubevirt_vmi_network_receive_bytes_total[1m])",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Network IO, transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kubevirt_vmi_network_transmit_bytes_total[1m])",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  }
 ]
}