apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: loadbalancer-ip
  values:
    controller:
      kind: DaemonSet
      service:
        type: LoadBalancer
        nodePorts:
          http: 30100
          https: 30101
        externalTrafficPolicy: Local
    ingress:
      enabled: true
      hosts:
        - kube.rnd-setup-ingress.fluence.dev
      ingressClassName: nginx
      # This will append our Ingress with annotations required by our default configuration.
      #    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      #    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      #    nginx.ingress.kubernetes.io/ssl-redirect: "true"
      useDefaultAnnotations: true
      pathType: ImplementationSpecific
      path: /
      issuer:
        name: selfsigned
        # Scope determines what kind of issuer annotation will be used on ingress resource
        # - default - adds 'cert-manager.io/issuer'
        # - cluster - adds 'cert-manager.io/cluster-issuer'
        # - disabled - disables cert-manager annotations
        scope: disabled
      tls:
        enabled: true
