apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: loadbalancer-ip
      valuesKey: externalIP
  values:
    controller:
      kind: DaemonSet
      service:
        type: LoadBalancer
        externalIPs:
          - '{{ values.externalIP }}'
        nodePorts:
          http: 30100
          https: 30101
        externalTrafficPolicy: Local
