apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./repository.yml
  - ./release.yml
configMapGenerator:
  - name: time-slicing-config-all
    files:
      - any=./time-slicing.yml
generatorOptions:
  disableNameSuffixHash: true
