apiVersion: v1
kind: Namespace
metadata:
  name: gpu-operator
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    digest-resolution: enabled
    pod-security.kubernetes.io/enforce: privileged
