apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: gpu-operator
      version: v24.9.2
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: gpu-operator
  # driftDetection:
  #   mode: enabled
  # install:
  #   crds: CreateReplace
  #   disableOpenAPIValidation: true
  #   remediation:
  #     retries: 3
  # upgrade:
  #   cleanupOnFail: true
  #   crds: CreateReplace
  #   disableOpenAPIValidation: true
  #   remediation:
  #     strategy: rollback
  #     retries: 3
  values:
    nfd:
      enabled: true
    gfd:
      enabled: false
    cdi:
      enabled: false
    # operator:
    #   repository: ghcr.io/jfroy
    #   version: v24.9.1
    #   defaultRuntime: containerd
    driver:
      enabled: false
    toolkit:
      enabled: false
    devicePlugin:
      enabled: false
      # config:
      #   name: time-slicing-config-all
      #   default: any
    dcgmExporter:
      enabled: false
    migManager:
      enabled: false
    vgpuDeviceManager:
      enabled: false
    vfioManager:
      enabled: true
    sandboxDevicePlugin:
      enabled: true
      defaultWorkload: "vm-passthrough"
    validator: {}
