name: cleanup

on:
  pull_request:
    types: [closed]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  destroy:
    uses: ./.github/workflows/terraform.yml
    with:
      command: "destroy"
      branch: ${{ github.event.pull_request.head.ref }}
      workspace: "spectrum-${{ github.event.pull_request.number }}"
    secrets:
      PAT: ${{ secrets.FLUENCEBOT_RELEASE_PLEASE_PAT }}
