name: cleanup

on:
  pull_request:
    types: [closed]

jobs:
  destroy:
    uses: ./.github/workflows/terraform.yml
    with:
      command: "destroy"
      branch: ${{ github.event.pull_request.head.ref }}
    secrets:
      PAT: ${{ secrets.FLUENCEBOT_RELEASE_PLEASE_PAT }}
