name: "create"

on:
  pull_request:
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"

jobs:
  k8s:
    if: >
        contains(github.event.pull_request.labels.*.name, 'ephemeral') &&
        !github.event.pull_request.head.repo.fork
    with:
      command: create
      workspace: "spectrum-${{ github.head_ref }}"
    secrets:
      PAT: ${{ secrets.FLUENCEBOT_RELEASE_PLEASE_PAT }}
