name: "create"

on:
  pull_request:
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  k8s:
    if: >
        contains(github.event.pull_request.labels.*.name, 'create') &&
        !github.event.pull_request.head.repo.fork
    uses: ./.github/workflows/terraform.yml
    with:
      command: create
      workspace: "spectrum-${{ github.event.number }}"
      branch: ${{ github.event.pull_request.head.ref }}
    secrets:
      PAT: ${{ secrets.FLUENCEBOT_RELEASE_PLEASE_PAT }}
