name: terraform

on:
  workflow_call:
    inputs:
      command:
        description: "The terraform command to run (create, destroy, reset)"
        required: true
        type: string
      workspace:
        description: "Workspace to use"
        required: true
        type: string
      branch:
        description: "Branch to checkout to"
        required: false
        type: string
        default: "main"
    secrets:
      PAT:
        description: "Used in Flux to clone the repo"
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ephemeral

    permissions:
      contents: read
      id-token: write

    env:
      TF_VAR_github_branch: ${{ inputs.branch }}
      TF_VAR_github_pr_url: ${{ github.event.pull_request.html_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: fluencelabs/spectrum
          ref: ${{ inputs.command == 'destroy' && 'main' || inputs.branch }}

      - name: Get Vault token
        uses: hashicorp/vault-action@v3.3.0
        with:
          url: "https://vault.fluence.dev"
          path: jwt/github
          role: ci-spectrum
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: true
          secrets: |
            kv/digitalocean/gitops token | DIGITALOCEAN_TOKEN ;
            kv/cloudflare/gitops token | CLOUDFLARE_API_TOKEN ;
            kv/ci/spectrum-ci id | AWS_ACCESS_KEY_ID ;
            kv/ci/spectrum-ci secret | AWS_SECRET_ACCESS_KEY ;

      - name: Sanitize prefix name
        id: sanitize
        run: |
          WORKSPACE="${{ inputs.workspace }}"
          # Sanitize for DNS compatibility
          WORKSPACE="${WORKSPACE//[^a-zA-Z0-9-]/-}"
          WORKSPACE="${WORKSPACE//+(-)/-}"
          WORKSPACE="${WORKSPACE,,}" # Convert to lowercase
          echo "workspace=${WORKSPACE}" >> $GITHUB_OUTPUT

      - name: Find comment
        if: inputs.command == 'create' || inputs.command == 'reset'
        uses: peter-evans/find-comment@v3
        id: comment
        with:
          token: ${{ secrets.PAT }}
          issue-number: "${{ github.event.pull_request.number }}"
          body-includes: "## ephemeral: ${{ steps.sanitize.outputs.workspace }}"

      - name: Add comment
        if: steps.comment.outputs.comment-id == null && (inputs.command == 'create' || inputs.command == 'reset')
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: "${{ steps.comment.outputs.comment-id }}"
          token: ${{ secrets.PAT }}
          issue-number: "${{ github.event.pull_request.number }}"
          body: |
            ## ephemeral: ${{ steps.sanitize.outputs.workspace }}
            Your instance is getting ready. Please wait.
          edit-mode: replace

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        if: always()
        run: terraform init

      - name: terraform workspace
        if: always()
        run: |
          terraform workspace select -or-create=true ${{ steps.sanitize.outputs.workspace }}

      - name: Run terraform command
        if: always()
        run: |
          case ${{ inputs.command }} in
          create)
            terraform apply -target module.talos.local_sensitive_file.kubeconfig -auto-approve
            terraform apply -auto-approve
          ;;
          destroy)
            terraform state rm \
              module.spectrum.helm_release.flux-sync \
              module.spectrum.helm_release.flux \
              module.spectrum.helm_release.cilium || true
            terraform destroy -auto-approve 
            terraform workspace select default
            terraform workspace delete ${{ steps.sanitize.outputs.workspace }} || true
          ;;
          reset)
            terraform state rm \
              module.spectrum.helm_release.flux-sync \
              module.spectrum.helm_release.flux \
              module.spectrum.helm_release.cilium
            terraform destroy -auto-approve
            terraform apply -auto-approve
          ;;
          *)
            echo "No such command ${{ inputs.command }}"
            exit 1
          ;;
          esac

      - name: Upload Artifacts
        if: inputs.command == 'create' || inputs.command == 'reset'
        uses: actions/upload-artifact@v4
        id: artifact
        with:
          name: configs
          path: |
            ephemeral/kubeconfig
            ephemeral/talosconfig

      - name: Find comment
        if: inputs.command == 'create' || inputs.command == 'reset'
        uses: peter-evans/find-comment@v3
        id: comment-update
        with:
          token: ${{ secrets.PAT }}
          issue-number: "${{ github.event.pull_request.number }}"
          body-includes: "## ephemeral: ${{ steps.sanitize.outputs.workspace }}"

      - name: Update comment
        if: inputs.command == 'create' || inputs.command == 'reset'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: "${{ steps.comment-update.outputs.comment-id }}"
          token: ${{ secrets.PAT }}
          issue-number: "${{ github.event.pull_request.number }}"
          body: |
            ## ephemeral: ${{ steps.sanitize.outputs.workspace }}
            Your ephemeral k8s cluster is ready.

            Visit the dashboard at https://home.${{ steps.sanitize.outputs.workspace }}.fluence.dev

            You can obtain kubeconfig and talos config from this [artifact](${{ steps.artifact.outputs.artifact-url }}).
            Download and unarchive the artifact, then run this command to export variables:
            ```shell
            [[ -f ./kubeconfig ]] && export KUBECONFIG=$(realpath ./kubeconfig)
            [[ -f ./talosconfig ]] && export TALOSCONFIG=$(realpath ./talosconfig)
            ```

            To get the token for kubernetes-dashboard auth run:
            ```shell
            kubectl -n kubernetes-dashboard create token kubernetes-dashboard-admin
            ```
          edit-mode: replace
