apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia
spec:
  interval: 30m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.17.0
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    config:
      map:
        default: |-
          version: v1
          flags:
            migStrategy: none
        mig-single: |-
          version: v1
          flags:
            migStrategy: single
        mig-mixed: |-
          version: v1
          flags:
            migStrategy: mixed
      # Default config name within the ConfigMap
      default: "mig-mixed"
      # List of fallback strategies to attempt if no config is selected and no default is provided
      fallbackStrategies: ["named" , "single"]
    runtimeClassName: nvidia

    gfd:
      enabled: true
