apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia
spec:
  interval: 30m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.17.0
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: nvidia
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    config:
      map:
        default: |-
          version: v1
          flags:
            migStrategy: none
        mig-single: |-
          version: v1
          flags:
            migStrategy: single
        mig-mixed: |-
          version: v1
          flags:
            migStrategy: mixed
        test: |-
          version: v1
          flags:
            migStrategy: none
          sharing:
            timeSlicing:
              renameByDefault: false
              failRequestsGreaterThanOne: false
              resources:
                - name: nvidia.com/gpu
                  replicas: 4
      default: "test"
      fallbackStrategies: ["named" , "single"]
    runtimeClassName: nvidia

    gfd:
      enabled: true
