apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - service-monitor.yml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
    app.kubernetes.io/part-of: spectrum-monitoring
    app.kubernetes.io/component: lightmare
commonAnnotations:
  grafana_folder: "Lightmare"

configMapGenerator:
  - name: dashboards-lightmare
    files:
      - dashboards/lightmare.json
