apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lightmare
  labels:
    app.kubernetes.io/part-of: spectrum-monitoring
    app.kubernetes.io/component: lightmare
spec:
  selector:
    matchLabels:
      app: lightmare
  namespaceSelector:
    matchNames:
    - lightmare
  endpoints:
  - port: metrics
    scheme: http
